DB_CONN_STR = "connection_string"
DB_USERNAME = "username"
DB_PASSWORD = "password"
DB_BUCKET = "bucket_name"
DB_SCOPE = "bucket_scope"
DB_COLLECTION = "bucket_collection"
INDEX_NAME = "index_name"
LOGIN_PASSWORD = "new_password_for_login"